sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t agni1984/rc-frontend -f Dockerfile .

script:
  - docker run -e CI=true agni1984/rc-frontend npm run test --passWithNoTests
