sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t agni1985/rc-frontend -f Dockerfile .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test
