sudo: required
language: generic
branches:
  only:
  - main

services:
  - docker

before_install:
  - docker build -t agni1984/rc-frontend -f Dockerfile .

script:
  - docker run -e CI=true agni1984/rc-frontend npm run test
deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'ResidentsConnect'
  env: 'ResidentsConnect-env'
  bucket_name: 'elasticbeanstalk-us-south-1-860905879962'
  bucket_path: 'ResidentsConnect'
  on:
    branch: main
  access_key_id: 'AKIA4Q4P5HGNKI65EYFG'
  secret_access_key: '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'
